import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from "node:fs";
import { createHash, randomUUID } from "node:crypto";
import { join } from "node:path";

export type Phase = "framing" | "generation" | "validation" | "synthesis" | "output";
export type AgentRole = "generator" | "extender" | "validator" | "literature" | "synthesizer" | "blindspot";
export type CandidateStatus = "proposed" | "validated" | "refuted" | "verified";
export interface FrameworkConfig { framework_version: string; target_repo_path: string; session_id: string; survivability: { danger_zone_tokens: number; checkpoint_margin_ratio: number; max_actions_between_checkpoints: number }; agent_roles: Record<AgentRole, { count_ratio: number; master_path: string }>; hazard_seed_ids: string[]; }
export interface Candidate { id: string; createdAt: string; phase: Phase; agentRole: AgentRole; question: string; approach: string; verificationCriterion: string; filePath: string; status: CandidateStatus; evidenceLinks: string[]; }
export interface ReproResult { candidateId: string; method: "counterexample" | "re-derivation" | "numerical-stress-test"; passed: boolean; filePath: string; log: string; }
export interface HazardEntry { id: string; family: string; description: string; discoveredIn: string; severity: "low" | "medium" | "high" | "critical"; }
export interface EvidenceRef { path: string; sha256: string; capturedAt: string; }
export interface SessionState { sessionId: string; phase: Phase; candidates: Record<string, Candidate>; repros: Record<string, ReproResult>; hazards: HazardEntry[]; deadends: string[]; evidence: Record<string, EvidenceRef>; completed: boolean; }
export interface CheckpointManifest { checkpointId: string; sequence: number; createdAt: string; stateSha256: string; phase: Phase; resumeBrief: string; }
export class MissingVerificationCriterionError extends Error { constructor(id: string) { super(`Candidate ${id} has no verification criterion.`); this.name = "MissingVerificationCriterionError"; } }
export class PrematurePhaseTransitionError extends Error { constructor(from: Phase, to: Phase, reason: string) { super(`Cannot transition ${from} -> ${to}: ${reason}`); this.name = "PrematurePhaseTransitionError"; } }
export class SessionCompletedError extends Error { constructor() { super("Research objective is already complete."); this.name = "SessionCompletedError"; } }
export class BrokenEvidenceChainError extends Error { constructor(candidateId: string, path: string) { super(`Evidence chain broken for ${candidateId}: ${path}`); this.name = "BrokenEvidenceChainError"; } }
export class InvalidSurvivabilityConfigError extends Error {}
export class TokenPressureTracker {
  private tokens = 0; private actions = 0;
  constructor(private readonly dangerZone: number, private readonly margin: number, private readonly maxActions: number) { if (dangerZone <= 0 || margin <= 0 || margin > 1 || maxActions <= 0) throw new InvalidSurvivabilityConfigError("Invalid survivability settings"); }
  record(estimatedTokens: number) { this.tokens += Math.max(0, Math.ceil(estimatedTokens)); this.actions++; return this.status(); }
  status() { const threshold = this.dangerZone * this.margin; return { estimatedTokens: this.tokens, actions: this.actions, checkpointRequired: this.tokens >= threshold || this.actions >= this.maxActions, reason: this.tokens >= threshold ? "token-pressure" : this.actions >= this.maxActions ? "action-count" : undefined }; }
  reset() { this.tokens = 0; this.actions = 0; }
}
const ORDER: Phase[] = ["framing", "generation", "validation", "synthesis", "output"];
export class ResearchEngine {
  private state: SessionState; private readonly statePath: string; private readonly checkpointDir: string; private readonly pressure: TokenPressureTracker; private mutationChain: Promise<unknown> = Promise.resolve();
  constructor(private readonly sessionRoot: string, private readonly config: FrameworkConfig) { this.statePath = join(sessionRoot, "state", "engine-state.json"); this.checkpointDir = join(sessionRoot, "state", "checkpoints"); this.pressure = new TokenPressureTracker(config.survivability.danger_zone_tokens, config.survivability.checkpoint_margin_ratio, config.survivability.max_actions_between_checkpoints); this.state = this.loadOrInit(); }
  private loadOrInit(): SessionState { const latest = this.latestCheckpoint(); if (latest) return this.readCheckpointState(latest); if (existsSync(this.statePath)) return JSON.parse(readFileSync(this.statePath, "utf8")); const state: SessionState = { sessionId: this.config.session_id, phase: "framing", candidates: {}, repros: {}, hazards: [], deadends: [], evidence: {}, completed: false }; this.persist(state); return state; }
  private persist(state = this.state) { const dir = join(this.sessionRoot, "state"); mkdirSync(dir, { recursive: true }); const tmp = `${this.statePath}.tmp-${randomUUID()}`; writeFileSync(tmp, JSON.stringify(state, null, 2), "utf8"); renameSync(tmp, this.statePath); appendFileSync(join(dir, "engine-audit.log"), `${new Date().toISOString()} phase=${state.phase} candidates=${Object.keys(state.candidates).length} completed=${state.completed}\n`); }
  private assertActive() { if (this.state.completed) throw new SessionCompletedError(); }
  private mutate<T>(fn: () => T): T { this.assertActive(); const out = fn(); this.persist(); return out; }
  getState(): Readonly<SessionState> { return this.state; }
  getPressureStatus() { return this.pressure.status(); }
  recordAction(estimatedTokens: number) { this.assertActive(); return this.pressure.record(estimatedTokens); }
  proposeCandidate(input: Omit<Candidate, "id" | "createdAt" | "status">): Candidate { return this.mutate(() => { if (!input.verificationCriterion.trim()) throw new MissingVerificationCriterionError(input.filePath); const hit = this.state.deadends.find(d => d.trim() && input.approach.toLowerCase().includes(d.toLowerCase())); if (hit) throw new PrematurePhaseTransitionError(this.state.phase, this.state.phase, `approach matches known deadend: ${hit}`); const candidate: Candidate = { ...input, id: randomUUID(), createdAt: new Date().toISOString(), status: "proposed" }; this.state.candidates[candidate.id] = candidate; return candidate; }); }
  logDeadend(description: string) { return this.mutate(() => { this.state.deadends.push(description); }); }
  registerHazard(hazard: HazardEntry) { return this.mutate(() => { this.state.hazards.push(hazard); }); }
  recordRepro(result: ReproResult) { return this.mutate(() => { const candidate = this.state.candidates[result.candidateId]; if (!candidate) throw new BrokenEvidenceChainError(result.candidateId, result.filePath); this.state.repros[result.filePath] = result; candidate.status = result.passed ? "validated" : "refuted"; if (!candidate.evidenceLinks.includes(result.filePath)) candidate.evidenceLinks.push(result.filePath); }); }
  promoteToVerified(candidateId: string): Candidate { return this.mutate(() => { const c = this.state.candidates[candidateId]; if (!c) throw new BrokenEvidenceChainError(candidateId, candidateId); const repro = Object.values(this.state.repros).find(r => r.candidateId === candidateId && r.passed); if (!repro) throw new PrematurePhaseTransitionError(this.state.phase, "synthesis", "no passing repro"); c.status = "verified"; return c; }); }
  advancePhase(): Phase { return this.mutate(() => { const i = ORDER.indexOf(this.state.phase); if (i < 0 || i === ORDER.length - 1) throw new PrematurePhaseTransitionError(this.state.phase, this.state.phase, "already at final phase"); const next = ORDER[i + 1]; if (this.state.phase === "generation" && !Object.values(this.state.candidates).some(c => !!c.verificationCriterion.trim())) throw new PrematurePhaseTransitionError(this.state.phase, next, "no candidate with verification criterion"); if (this.state.phase === "validation" && !Object.values(this.state.candidates).some(c => c.status === "validated")) throw new PrematurePhaseTransitionError(this.state.phase, next, "no validated candidate"); if (this.state.phase === "synthesis" && !Object.values(this.state.candidates).some(c => c.status === "verified")) throw new PrematurePhaseTransitionError(this.state.phase, next, "no verified candidate"); this.state.phase = next; return next; }); }
  validateEvidenceChain() { const breaks: { candidateId: string; missingPath: string }[] = []; for (const c of Object.values(this.state.candidates)) for (const p of c.evidenceLinks) if (!existsSync(join(this.sessionRoot, p))) breaks.push({ candidateId: c.id, missingPath: p }); return { ok: breaks.length === 0, breaks }; }
  captureEvidence(candidateId: string, relativePath: string): EvidenceRef { return this.mutate(() => { const c = this.state.candidates[candidateId]; if (!c) throw new BrokenEvidenceChainError(candidateId, relativePath); const absolute = join(this.sessionRoot, relativePath); if (!existsSync(absolute)) throw new BrokenEvidenceChainError(candidateId, relativePath); const sha256 = createHash("sha256").update(readFileSync(absolute)).digest("hex"); const ref = { path: relativePath, sha256, capturedAt: new Date().toISOString() }; this.state.evidence[relativePath] = ref; if (!c.evidenceLinks.includes(relativePath)) c.evidenceLinks.push(relativePath); return ref; }); }
  verifyEvidenceIntegrity() { const breaks: string[] = []; for (const ref of Object.values(this.state.evidence)) { const absolute = join(this.sessionRoot, ref.path); if (!existsSync(absolute) || createHash("sha256").update(readFileSync(absolute)).digest("hex") !== ref.sha256) breaks.push(ref.path); } return { ok: breaks.length === 0, breaks }; }
  declareObjectiveComplete(note: string) { return this.mutate(() => { if (!Object.values(this.state.candidates).some(c => c.status === "verified")) throw new PrematurePhaseTransitionError(this.state.phase, "output", "cannot complete without a verified candidate"); this.state.completed = true; this.state.hazards.push({ id: `completion-${randomUUID()}`, family: "lifecycle", description: note, discoveredIn: "completion", severity: "low" }); }); }
  writeCheckpoint(resumeBrief: string): CheckpointManifest { this.assertActive(); mkdirSync(this.checkpointDir, { recursive: true }); const sequence = this.latestCheckpoint()?.sequence ?? 0; const checkpointId = `${String(sequence + 1).padStart(6, "0")}-${randomUUID()}`; const stateJson = JSON.stringify(this.state, null, 2); const stateSha256 = createHash("sha256").update(stateJson).digest("hex"); const manifest: CheckpointManifest = { checkpointId, sequence: sequence + 1, createdAt: new Date().toISOString(), stateSha256, phase: this.state.phase, resumeBrief }; const payload = { manifest, state: this.state }; const tmp = join(this.checkpointDir, `.${checkpointId}.tmp`); const final = join(this.checkpointDir, `${checkpointId}.json`); writeFileSync(tmp, JSON.stringify(payload, null, 2), "utf8"); renameSync(tmp, final); this.persist(); this.pressure.reset(); return manifest; }
  getResumeBrief(): string | null { return this.latestCheckpoint()?.resumeBrief ?? null; }
  private latestCheckpoint(): CheckpointManifest | null { if (!existsSync(this.checkpointDir)) return null; const files = readdirSync(this.checkpointDir).filter(f => f.endsWith(".json")).sort(); if (!files.length) return null; return JSON.parse(readFileSync(join(this.checkpointDir, files[files.length - 1]), "utf8")).manifest; }
  private readCheckpointState(manifest: CheckpointManifest): SessionState { const files = readdirSync(this.checkpointDir).filter(f => f.endsWith(".json")).sort(); const file = files[files.length - 1]; const payload = JSON.parse(readFileSync(join(this.checkpointDir, file), "utf8")); const hash = createHash("sha256").update(JSON.stringify(payload.state, null, 2)).digest("hex"); if (hash !== manifest.stateSha256) throw new Error(`Checkpoint integrity failure: ${manifest.checkpointId}`); return payload.state; }
  async serialize<T>(fn: () => Promise<T> | T): Promise<T> { const previous = this.mutationChain; let release!: () => void; this.mutationChain = new Promise<void>(r => { release = r; }); await previous; try { return await fn(); } finally { release(); } }
}
